// agent.proto — agent 通道与 enrollment 的 gRPC 契约（架构 v1.1.2 §8.2、spec §11）。
// 生成代码入库；再生成方式见 api/proto/gen.sh。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: fleet/v1/agent.proto

package fleetv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AgentToServer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*AgentToServer_Hello
	//	*AgentToServer_Heartbeat
	//	*AgentToServer_ObservedState
	//	*AgentToServer_OperationStarted
	//	*AgentToServer_OperationProgress
	//	*AgentToServer_OperationResult
	//	*AgentToServer_LogEvent
	Payload       isAgentToServer_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentToServer) Reset() {
	*x = AgentToServer{}
	mi := &file_fleet_v1_agent_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentToServer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentToServer) ProtoMessage() {}

func (x *AgentToServer) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_agent_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentToServer.ProtoReflect.Descriptor instead.
func (*AgentToServer) Descriptor() ([]byte, []int) {
	return file_fleet_v1_agent_proto_rawDescGZIP(), []int{0}
}

func (x *AgentToServer) GetPayload() isAgentToServer_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *AgentToServer) GetHello() *Hello {
	if x != nil {
		if x, ok := x.Payload.(*AgentToServer_Hello); ok {
			return x.Hello
		}
	}
	return nil
}

func (x *AgentToServer) GetHeartbeat() *Heartbeat {
	if x != nil {
		if x, ok := x.Payload.(*AgentToServer_Heartbeat); ok {
			return x.Heartbeat
		}
	}
	return nil
}

func (x *AgentToServer) GetObservedState() *ObservedState {
	if x != nil {
		if x, ok := x.Payload.(*AgentToServer_ObservedState); ok {
			return x.ObservedState
		}
	}
	return nil
}

func (x *AgentToServer) GetOperationStarted() *OperationStarted {
	if x != nil {
		if x, ok := x.Payload.(*AgentToServer_OperationStarted); ok {
			return x.OperationStarted
		}
	}
	return nil
}

func (x *AgentToServer) GetOperationProgress() *OperationProgress {
	if x != nil {
		if x, ok := x.Payload.(*AgentToServer_OperationProgress); ok {
			return x.OperationProgress
		}
	}
	return nil
}

func (x *AgentToServer) GetOperationResult() *OperationResult {
	if x != nil {
		if x, ok := x.Payload.(*AgentToServer_OperationResult); ok {
			return x.OperationResult
		}
	}
	return nil
}

func (x *AgentToServer) GetLogEvent() *LogEvent {
	if x != nil {
		if x, ok := x.Payload.(*AgentToServer_LogEvent); ok {
			return x.LogEvent
		}
	}
	return nil
}

type isAgentToServer_Payload interface {
	isAgentToServer_Payload()
}

type AgentToServer_Hello struct {
	Hello *Hello `protobuf:"bytes,1,opt,name=hello,proto3,oneof"`
}

type AgentToServer_Heartbeat struct {
	Heartbeat *Heartbeat `protobuf:"bytes,2,opt,name=heartbeat,proto3,oneof"`
}

type AgentToServer_ObservedState struct {
	ObservedState *ObservedState `protobuf:"bytes,3,opt,name=observed_state,json=observedState,proto3,oneof"`
}

type AgentToServer_OperationStarted struct {
	OperationStarted *OperationStarted `protobuf:"bytes,4,opt,name=operation_started,json=operationStarted,proto3,oneof"`
}

type AgentToServer_OperationProgress struct {
	OperationProgress *OperationProgress `protobuf:"bytes,5,opt,name=operation_progress,json=operationProgress,proto3,oneof"`
}

type AgentToServer_OperationResult struct {
	OperationResult *OperationResult `protobuf:"bytes,6,opt,name=operation_result,json=operationResult,proto3,oneof"`
}

type AgentToServer_LogEvent struct {
	LogEvent *LogEvent `protobuf:"bytes,7,opt,name=log_event,json=logEvent,proto3,oneof"`
}

func (*AgentToServer_Hello) isAgentToServer_Payload() {}

func (*AgentToServer_Heartbeat) isAgentToServer_Payload() {}

func (*AgentToServer_ObservedState) isAgentToServer_Payload() {}

func (*AgentToServer_OperationStarted) isAgentToServer_Payload() {}

func (*AgentToServer_OperationProgress) isAgentToServer_Payload() {}

func (*AgentToServer_OperationResult) isAgentToServer_Payload() {}

func (*AgentToServer_LogEvent) isAgentToServer_Payload() {}

type ServerToAgent struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Payload:
	//
	//	*ServerToAgent_Welcome
	//	*ServerToAgent_DesiredStateChanged
	//	*ServerToAgent_ExecuteOperation
	//	*ServerToAgent_CancelOperation
	//	*ServerToAgent_OperationResultAck
	//	*ServerToAgent_RequestInventory
	Payload       isServerToAgent_Payload `protobuf_oneof:"payload"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ServerToAgent) Reset() {
	*x = ServerToAgent{}
	mi := &file_fleet_v1_agent_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ServerToAgent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ServerToAgent) ProtoMessage() {}

func (x *ServerToAgent) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_agent_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ServerToAgent.ProtoReflect.Descriptor instead.
func (*ServerToAgent) Descriptor() ([]byte, []int) {
	return file_fleet_v1_agent_proto_rawDescGZIP(), []int{1}
}

func (x *ServerToAgent) GetPayload() isServerToAgent_Payload {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *ServerToAgent) GetWelcome() *Welcome {
	if x != nil {
		if x, ok := x.Payload.(*ServerToAgent_Welcome); ok {
			return x.Welcome
		}
	}
	return nil
}

func (x *ServerToAgent) GetDesiredStateChanged() *DesiredStateChanged {
	if x != nil {
		if x, ok := x.Payload.(*ServerToAgent_DesiredStateChanged); ok {
			return x.DesiredStateChanged
		}
	}
	return nil
}

func (x *ServerToAgent) GetExecuteOperation() *ExecuteOperation {
	if x != nil {
		if x, ok := x.Payload.(*ServerToAgent_ExecuteOperation); ok {
			return x.ExecuteOperation
		}
	}
	return nil
}

func (x *ServerToAgent) GetCancelOperation() *CancelOperation {
	if x != nil {
		if x, ok := x.Payload.(*ServerToAgent_CancelOperation); ok {
			return x.CancelOperation
		}
	}
	return nil
}

func (x *ServerToAgent) GetOperationResultAck() *OperationResultAck {
	if x != nil {
		if x, ok := x.Payload.(*ServerToAgent_OperationResultAck); ok {
			return x.OperationResultAck
		}
	}
	return nil
}

func (x *ServerToAgent) GetRequestInventory() *RequestInventory {
	if x != nil {
		if x, ok := x.Payload.(*ServerToAgent_RequestInventory); ok {
			return x.RequestInventory
		}
	}
	return nil
}

type isServerToAgent_Payload interface {
	isServerToAgent_Payload()
}

type ServerToAgent_Welcome struct {
	Welcome *Welcome `protobuf:"bytes,1,opt,name=welcome,proto3,oneof"`
}

type ServerToAgent_DesiredStateChanged struct {
	DesiredStateChanged *DesiredStateChanged `protobuf:"bytes,2,opt,name=desired_state_changed,json=desiredStateChanged,proto3,oneof"`
}

type ServerToAgent_ExecuteOperation struct {
	ExecuteOperation *ExecuteOperation `protobuf:"bytes,3,opt,name=execute_operation,json=executeOperation,proto3,oneof"`
}

type ServerToAgent_CancelOperation struct {
	CancelOperation *CancelOperation `protobuf:"bytes,4,opt,name=cancel_operation,json=cancelOperation,proto3,oneof"`
}

type ServerToAgent_OperationResultAck struct {
	OperationResultAck *OperationResultAck `protobuf:"bytes,5,opt,name=operation_result_ack,json=operationResultAck,proto3,oneof"`
}

type ServerToAgent_RequestInventory struct {
	RequestInventory *RequestInventory `protobuf:"bytes,6,opt,name=request_inventory,json=requestInventory,proto3,oneof"`
}

func (*ServerToAgent_Welcome) isServerToAgent_Payload() {}

func (*ServerToAgent_DesiredStateChanged) isServerToAgent_Payload() {}

func (*ServerToAgent_ExecuteOperation) isServerToAgent_Payload() {}

func (*ServerToAgent_CancelOperation) isServerToAgent_Payload() {}

func (*ServerToAgent_OperationResultAck) isServerToAgent_Payload() {}

func (*ServerToAgent_RequestInventory) isServerToAgent_Payload() {}

type Hello struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// machine_id 必须与客户端证书身份一致（§7.5 身份绑定）。
	MachineId       string `protobuf:"bytes,1,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	AgentdVersion   string `protobuf:"bytes,2,opt,name=agentd_version,json=agentdVersion,proto3" json:"agentd_version,omitempty"`
	ProtocolVersion string `protobuf:"bytes,3,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	// 支持的 adapter 家族与投影规范化版本（§7.6 版本协商）。
	Adapters                []string `protobuf:"bytes,4,rep,name=adapters,proto3" json:"adapters,omitempty"`
	CanonicalizationVersion string   `protobuf:"bytes,5,opt,name=canonicalization_version,json=canonicalizationVersion,proto3" json:"canonicalization_version,omitempty"`
	LastInventorySeq        int64    `protobuf:"varint,6,opt,name=last_inventory_seq,json=lastInventorySeq,proto3" json:"last_inventory_seq,omitempty"`
	// 能力声明（支持矩阵「统一适配契约」）：逐家族声明支持/不支持/未验证与
	// 已验证版本范围，通过既有能力协商暴露给控制面；控制面只读取声明，
	// 不硬编码各家族路径。
	Capabilities  []*AdapterCapability `protobuf:"bytes,7,rep,name=capabilities,proto3" json:"capabilities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Hello) Reset() {
	*x = Hello{}
	mi := &file_fleet_v1_agent_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Hello) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Hello) ProtoMessage() {}

func (x *Hello) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_agent_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Hello.ProtoReflect.Descriptor instead.
func (*Hello) Descriptor() ([]byte, []int) {
	return file_fleet_v1_agent_proto_rawDescGZIP(), []int{2}
}

func (x *Hello) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *Hello) GetAgentdVersion() string {
	if x != nil {
		return x.AgentdVersion
	}
	return ""
}

func (x *Hello) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *Hello) GetAdapters() []string {
	if x != nil {
		return x.Adapters
	}
	return nil
}

func (x *Hello) GetCanonicalizationVersion() string {
	if x != nil {
		return x.CanonicalizationVersion
	}
	return ""
}

func (x *Hello) GetLastInventorySeq() int64 {
	if x != nil {
		return x.LastInventorySeq
	}
	return 0
}

func (x *Hello) GetCapabilities() []*AdapterCapability {
	if x != nil {
		return x.Capabilities
	}
	return nil
}

// AdapterCapability 是一条家族能力声明（矩阵：未知能力不得当作支持）。
type AdapterCapability struct {
	state  protoimpl.MessageState `protogen:"open.v1"`
	Family string                 `protobuf:"bytes,1,opt,name=family,proto3" json:"family,omitempty"`
	// version | modelProvider | mcp | skills | rules
	Capability string `protobuf:"bytes,2,opt,name=capability,proto3" json:"capability,omitempty"`
	// supported | unsupported | unverified
	State string `protobuf:"bytes,3,opt,name=state,proto3" json:"state,omitempty"`
	// 结论成立的运行时版本范围（未验证时为空）。
	VerifiedVersions string `protobuf:"bytes,4,opt,name=verified_versions,json=verifiedVersions,proto3" json:"verified_versions,omitempty"`
	// unsupported/unverified 的具体原因（人读）。
	Reason        string `protobuf:"bytes,5,opt,name=reason,proto3" json:"reason,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AdapterCapability) Reset() {
	*x = AdapterCapability{}
	mi := &file_fleet_v1_agent_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AdapterCapability) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AdapterCapability) ProtoMessage() {}

func (x *AdapterCapability) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_agent_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AdapterCapability.ProtoReflect.Descriptor instead.
func (*AdapterCapability) Descriptor() ([]byte, []int) {
	return file_fleet_v1_agent_proto_rawDescGZIP(), []int{3}
}

func (x *AdapterCapability) GetFamily() string {
	if x != nil {
		return x.Family
	}
	return ""
}

func (x *AdapterCapability) GetCapability() string {
	if x != nil {
		return x.Capability
	}
	return ""
}

func (x *AdapterCapability) GetState() string {
	if x != nil {
		return x.State
	}
	return ""
}

func (x *AdapterCapability) GetVerifiedVersions() string {
	if x != nil {
		return x.VerifiedVersions
	}
	return ""
}

func (x *AdapterCapability) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

type Welcome struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	ProtocolVersion string                 `protobuf:"bytes,1,opt,name=protocol_version,json=protocolVersion,proto3" json:"protocol_version,omitempty"`
	// 服务端配置回传：心跳与全量 inventory 的期望周期（秒）。
	HeartbeatIntervalSeconds int32 `protobuf:"varint,2,opt,name=heartbeat_interval_seconds,json=heartbeatIntervalSeconds,proto3" json:"heartbeat_interval_seconds,omitempty"`
	InventoryIntervalSeconds int32 `protobuf:"varint,3,opt,name=inventory_interval_seconds,json=inventoryIntervalSeconds,proto3" json:"inventory_interval_seconds,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *Welcome) Reset() {
	*x = Welcome{}
	mi := &file_fleet_v1_agent_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Welcome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Welcome) ProtoMessage() {}

func (x *Welcome) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_agent_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Welcome.ProtoReflect.Descriptor instead.
func (*Welcome) Descriptor() ([]byte, []int) {
	return file_fleet_v1_agent_proto_rawDescGZIP(), []int{4}
}

func (x *Welcome) GetProtocolVersion() string {
	if x != nil {
		return x.ProtocolVersion
	}
	return ""
}

func (x *Welcome) GetHeartbeatIntervalSeconds() int32 {
	if x != nil {
		return x.HeartbeatIntervalSeconds
	}
	return 0
}

func (x *Welcome) GetInventoryIntervalSeconds() int32 {
	if x != nil {
		return x.InventoryIntervalSeconds
	}
	return 0
}

type Heartbeat struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Sequence int64                  `protobuf:"varint,1,opt,name=sequence,proto3" json:"sequence,omitempty"`
	// 节点发送时刻（unix 秒）。节点时钟不被信任，仅作诊断；服务端以接收时间为准。
	SentAtUnix    int64 `protobuf:"varint,2,opt,name=sent_at_unix,json=sentAtUnix,proto3" json:"sent_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Heartbeat) Reset() {
	*x = Heartbeat{}
	mi := &file_fleet_v1_agent_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Heartbeat) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Heartbeat) ProtoMessage() {}

func (x *Heartbeat) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_agent_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Heartbeat.ProtoReflect.Descriptor instead.
func (*Heartbeat) Descriptor() ([]byte, []int) {
	return file_fleet_v1_agent_proto_rawDescGZIP(), []int{5}
}

func (x *Heartbeat) GetSequence() int64 {
	if x != nil {
		return x.Sequence
	}
	return 0
}

func (x *Heartbeat) GetSentAtUnix() int64 {
	if x != nil {
		return x.SentAtUnix
	}
	return 0
}

type DesiredStateChanged struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Generation    int64                  `protobuf:"varint,1,opt,name=generation,proto3" json:"generation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DesiredStateChanged) Reset() {
	*x = DesiredStateChanged{}
	mi := &file_fleet_v1_agent_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DesiredStateChanged) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesiredStateChanged) ProtoMessage() {}

func (x *DesiredStateChanged) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_agent_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesiredStateChanged.ProtoReflect.Descriptor instead.
func (*DesiredStateChanged) Descriptor() ([]byte, []int) {
	return file_fleet_v1_agent_proto_rawDescGZIP(), []int{6}
}

func (x *DesiredStateChanged) GetGeneration() int64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

// DesiredStateSnapshot 自包含下发（FR-13.6：ExecuteOperation 一律携带完整快照；
// 节点冷启动无本地缓存也能执行）。
type DesiredStateSnapshot struct {
	state      protoimpl.MessageState `protogen:"open.v1"`
	Generation int64                  `protobuf:"varint,1,opt,name=generation,proto3" json:"generation,omitempty"`
	// 规范化 JSON 的确定性 SHA-256（snapshotDigest，§4.8）。
	Digest        string `protobuf:"bytes,2,opt,name=digest,proto3" json:"digest,omitempty"`
	SnapshotJson  []byte `protobuf:"bytes,3,opt,name=snapshot_json,json=snapshotJson,proto3" json:"snapshot_json,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DesiredStateSnapshot) Reset() {
	*x = DesiredStateSnapshot{}
	mi := &file_fleet_v1_agent_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DesiredStateSnapshot) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DesiredStateSnapshot) ProtoMessage() {}

func (x *DesiredStateSnapshot) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_agent_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DesiredStateSnapshot.ProtoReflect.Descriptor instead.
func (*DesiredStateSnapshot) Descriptor() ([]byte, []int) {
	return file_fleet_v1_agent_proto_rawDescGZIP(), []int{7}
}

func (x *DesiredStateSnapshot) GetGeneration() int64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

func (x *DesiredStateSnapshot) GetDigest() string {
	if x != nil {
		return x.Digest
	}
	return ""
}

func (x *DesiredStateSnapshot) GetSnapshotJson() []byte {
	if x != nil {
		return x.SnapshotJson
	}
	return nil
}

// PlanBaseline 是"计划所基于的观测基线"（FR-12.7 点名的两项：观测受管摘要 +
// inventorySeq）。KM-26 补入协议：apply 前重算基线必须与之比对，不一致即拒绝执行、
// 零变更、报 ReplanRequired。
type PlanBaseline struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	ObservedProjectionDigest string                 `protobuf:"bytes,1,opt,name=observed_projection_digest,json=observedProjectionDigest,proto3" json:"observed_projection_digest,omitempty"`
	InventorySeq             int64                  `protobuf:"varint,2,opt,name=inventory_seq,json=inventorySeq,proto3" json:"inventory_seq,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *PlanBaseline) Reset() {
	*x = PlanBaseline{}
	mi := &file_fleet_v1_agent_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PlanBaseline) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlanBaseline) ProtoMessage() {}

func (x *PlanBaseline) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_agent_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlanBaseline.ProtoReflect.Descriptor instead.
func (*PlanBaseline) Descriptor() ([]byte, []int) {
	return file_fleet_v1_agent_proto_rawDescGZIP(), []int{8}
}

func (x *PlanBaseline) GetObservedProjectionDigest() string {
	if x != nil {
		return x.ObservedProjectionDigest
	}
	return ""
}

func (x *PlanBaseline) GetInventorySeq() int64 {
	if x != nil {
		return x.InventorySeq
	}
	return 0
}

// ExecuteOperation 携带完整快照（FR-13.6：一律自包含）。
type ExecuteOperation struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OperationId       string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	DesiredGeneration int64                  `protobuf:"varint,2,opt,name=desired_generation,json=desiredGeneration,proto3" json:"desired_generation,omitempty"`
	Snapshot          *DesiredStateSnapshot  `protobuf:"bytes,3,opt,name=snapshot,proto3" json:"snapshot,omitempty"`
	// plan_digest 是操作者确认的那份计划（确认对象是具体计划，不是仅目标代）。
	PlanDigest string `protobuf:"bytes,4,opt,name=plan_digest,json=planDigest,proto3" json:"plan_digest,omitempty"`
	// baseline 非空时，节点必须重取观测、重算基线并与它比对（FR-12.7）。
	Baseline      *PlanBaseline `protobuf:"bytes,5,opt,name=baseline,proto3" json:"baseline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ExecuteOperation) Reset() {
	*x = ExecuteOperation{}
	mi := &file_fleet_v1_agent_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ExecuteOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ExecuteOperation) ProtoMessage() {}

func (x *ExecuteOperation) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_agent_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ExecuteOperation.ProtoReflect.Descriptor instead.
func (*ExecuteOperation) Descriptor() ([]byte, []int) {
	return file_fleet_v1_agent_proto_rawDescGZIP(), []int{9}
}

func (x *ExecuteOperation) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *ExecuteOperation) GetDesiredGeneration() int64 {
	if x != nil {
		return x.DesiredGeneration
	}
	return 0
}

func (x *ExecuteOperation) GetSnapshot() *DesiredStateSnapshot {
	if x != nil {
		return x.Snapshot
	}
	return nil
}

func (x *ExecuteOperation) GetPlanDigest() string {
	if x != nil {
		return x.PlanDigest
	}
	return ""
}

func (x *ExecuteOperation) GetBaseline() *PlanBaseline {
	if x != nil {
		return x.Baseline
	}
	return nil
}

// OperationStarted / OperationProgress / OperationResult 为变更流水线上报
// （本片仅定义消息并做幂等接收；执行流水线随第 3 片实现）。
type OperationStarted struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationStarted) Reset() {
	*x = OperationStarted{}
	mi := &file_fleet_v1_agent_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationStarted) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationStarted) ProtoMessage() {}

func (x *OperationStarted) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_agent_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationStarted.ProtoReflect.Descriptor instead.
func (*OperationStarted) Descriptor() ([]byte, []int) {
	return file_fleet_v1_agent_proto_rawDescGZIP(), []int{10}
}

func (x *OperationStarted) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

type OperationProgress struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	Step          string                 `protobuf:"bytes,2,opt,name=step,proto3" json:"step,omitempty"`
	Phase         string                 `protobuf:"bytes,3,opt,name=phase,proto3" json:"phase,omitempty"`
	Message       string                 `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationProgress) Reset() {
	*x = OperationProgress{}
	mi := &file_fleet_v1_agent_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationProgress) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationProgress) ProtoMessage() {}

func (x *OperationProgress) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_agent_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationProgress.ProtoReflect.Descriptor instead.
func (*OperationProgress) Descriptor() ([]byte, []int) {
	return file_fleet_v1_agent_proto_rawDescGZIP(), []int{11}
}

func (x *OperationProgress) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *OperationProgress) GetStep() string {
	if x != nil {
		return x.Step
	}
	return ""
}

func (x *OperationProgress) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *OperationProgress) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

type OperationResult struct {
	state       protoimpl.MessageState `protogen:"open.v1"`
	OperationId string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	// 终态 phase（§6.4）；服务端按 operationId 幂等去重（spec §11.5）。
	Phase             string          `protobuf:"bytes,2,opt,name=phase,proto3" json:"phase,omitempty"`
	Reason            string          `protobuf:"bytes,3,opt,name=reason,proto3" json:"reason,omitempty"`
	Message           string          `protobuf:"bytes,4,opt,name=message,proto3" json:"message,omitempty"`
	DesiredGeneration int64           `protobuf:"varint,5,opt,name=desired_generation,json=desiredGeneration,proto3" json:"desired_generation,omitempty"`
	Verify            *VerifyEvidence `protobuf:"bytes,6,opt,name=verify,proto3" json:"verify,omitempty"`
	StartedAtUnix     int64           `protobuf:"varint,7,opt,name=started_at_unix,json=startedAtUnix,proto3" json:"started_at_unix,omitempty"`
	FinishedAtUnix    int64           `protobuf:"varint,8,opt,name=finished_at_unix,json=finishedAtUnix,proto3" json:"finished_at_unix,omitempty"`
	// terminal_modifier 是节点侧终态修饰（KM-23：取消终结 Failed(Cancelled)
	// 时携带 "Cancelled"；服务端迟到成功记 "Superseded"，§6.4）。
	TerminalModifier string `protobuf:"bytes,9,opt,name=terminal_modifier,json=terminalModifier,proto3" json:"terminal_modifier,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *OperationResult) Reset() {
	*x = OperationResult{}
	mi := &file_fleet_v1_agent_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationResult) ProtoMessage() {}

func (x *OperationResult) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_agent_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationResult.ProtoReflect.Descriptor instead.
func (*OperationResult) Descriptor() ([]byte, []int) {
	return file_fleet_v1_agent_proto_rawDescGZIP(), []int{12}
}

func (x *OperationResult) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *OperationResult) GetPhase() string {
	if x != nil {
		return x.Phase
	}
	return ""
}

func (x *OperationResult) GetReason() string {
	if x != nil {
		return x.Reason
	}
	return ""
}

func (x *OperationResult) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *OperationResult) GetDesiredGeneration() int64 {
	if x != nil {
		return x.DesiredGeneration
	}
	return 0
}

func (x *OperationResult) GetVerify() *VerifyEvidence {
	if x != nil {
		return x.Verify
	}
	return nil
}

func (x *OperationResult) GetStartedAtUnix() int64 {
	if x != nil {
		return x.StartedAtUnix
	}
	return 0
}

func (x *OperationResult) GetFinishedAtUnix() int64 {
	if x != nil {
		return x.FinishedAtUnix
	}
	return 0
}

func (x *OperationResult) GetTerminalModifier() string {
	if x != nil {
		return x.TerminalModifier
	}
	return ""
}

// VerifyEvidence 是绑定 operationId 的门禁与审计证据（§6.4）。
type VerifyEvidence struct {
	state                    protoimpl.MessageState `protogen:"open.v1"`
	DesiredProjectionDigest  string                 `protobuf:"bytes,1,opt,name=desired_projection_digest,json=desiredProjectionDigest,proto3" json:"desired_projection_digest,omitempty"`
	ObservedProjectionDigest string                 `protobuf:"bytes,2,opt,name=observed_projection_digest,json=observedProjectionDigest,proto3" json:"observed_projection_digest,omitempty"`
	CanonicalizationVersion  string                 `protobuf:"bytes,3,opt,name=canonicalization_version,json=canonicalizationVersion,proto3" json:"canonicalization_version,omitempty"`
	InventorySeq             int64                  `protobuf:"varint,4,opt,name=inventory_seq,json=inventorySeq,proto3" json:"inventory_seq,omitempty"`
	AdapterHealth            string                 `protobuf:"bytes,5,opt,name=adapter_health,json=adapterHealth,proto3" json:"adapter_health,omitempty"` // passed | failed | skipped
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *VerifyEvidence) Reset() {
	*x = VerifyEvidence{}
	mi := &file_fleet_v1_agent_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyEvidence) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyEvidence) ProtoMessage() {}

func (x *VerifyEvidence) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_agent_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyEvidence.ProtoReflect.Descriptor instead.
func (*VerifyEvidence) Descriptor() ([]byte, []int) {
	return file_fleet_v1_agent_proto_rawDescGZIP(), []int{13}
}

func (x *VerifyEvidence) GetDesiredProjectionDigest() string {
	if x != nil {
		return x.DesiredProjectionDigest
	}
	return ""
}

func (x *VerifyEvidence) GetObservedProjectionDigest() string {
	if x != nil {
		return x.ObservedProjectionDigest
	}
	return ""
}

func (x *VerifyEvidence) GetCanonicalizationVersion() string {
	if x != nil {
		return x.CanonicalizationVersion
	}
	return ""
}

func (x *VerifyEvidence) GetInventorySeq() int64 {
	if x != nil {
		return x.InventorySeq
	}
	return 0
}

func (x *VerifyEvidence) GetAdapterHealth() string {
	if x != nil {
		return x.AdapterHealth
	}
	return ""
}

// CancelOperation 语义见 §9.7（随第 3 片派发）。
type CancelOperation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CancelOperation) Reset() {
	*x = CancelOperation{}
	mi := &file_fleet_v1_agent_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CancelOperation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CancelOperation) ProtoMessage() {}

func (x *CancelOperation) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_agent_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CancelOperation.ProtoReflect.Descriptor instead.
func (*CancelOperation) Descriptor() ([]byte, []int) {
	return file_fleet_v1_agent_proto_rawDescGZIP(), []int{14}
}

func (x *CancelOperation) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

// OperationResultAck 是 outbox 淘汰依据（§5.2）。
type OperationResultAck struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OperationId   string                 `protobuf:"bytes,1,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OperationResultAck) Reset() {
	*x = OperationResultAck{}
	mi := &file_fleet_v1_agent_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OperationResultAck) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OperationResultAck) ProtoMessage() {}

func (x *OperationResultAck) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_agent_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OperationResultAck.ProtoReflect.Descriptor instead.
func (*OperationResultAck) Descriptor() ([]byte, []int) {
	return file_fleet_v1_agent_proto_rawDescGZIP(), []int{15}
}

func (x *OperationResultAck) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

type RequestInventory struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Full          bool                   `protobuf:"varint,1,opt,name=full,proto3" json:"full,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RequestInventory) Reset() {
	*x = RequestInventory{}
	mi := &file_fleet_v1_agent_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RequestInventory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RequestInventory) ProtoMessage() {}

func (x *RequestInventory) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_agent_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RequestInventory.ProtoReflect.Descriptor instead.
func (*RequestInventory) Descriptor() ([]byte, []int) {
	return file_fleet_v1_agent_proto_rawDescGZIP(), []int{16}
}

func (x *RequestInventory) GetFull() bool {
	if x != nil {
		return x.Full
	}
	return false
}

// LogEvent 仅运维日志，禁止携带 Agent 会话内容（spec §11.3）。
type LogEvent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Level         string                 `protobuf:"bytes,1,opt,name=level,proto3" json:"level,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	SentAtUnix    int64                  `protobuf:"varint,3,opt,name=sent_at_unix,json=sentAtUnix,proto3" json:"sent_at_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LogEvent) Reset() {
	*x = LogEvent{}
	mi := &file_fleet_v1_agent_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LogEvent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LogEvent) ProtoMessage() {}

func (x *LogEvent) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_agent_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LogEvent.ProtoReflect.Descriptor instead.
func (*LogEvent) Descriptor() ([]byte, []int) {
	return file_fleet_v1_agent_proto_rawDescGZIP(), []int{17}
}

func (x *LogEvent) GetLevel() string {
	if x != nil {
		return x.Level
	}
	return ""
}

func (x *LogEvent) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *LogEvent) GetSentAtUnix() int64 {
	if x != nil {
		return x.SentAtUnix
	}
	return 0
}

type EnrollRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// machine_id 为 Machine 名称（沿用库中 machines.name 键约定）。
	MachineId string `protobuf:"bytes,1,opt,name=machine_id,json=machineId,proto3" json:"machine_id,omitempty"`
	// enrollment token（一次性、短时效、熵 ≥128-bit；绑定 machineId 与 CSR 指纹）。
	Token string `protobuf:"bytes,2,opt,name=token,proto3" json:"token,omitempty"`
	// PEM 编码的 PKCS#10 CSR。
	CsrPem        []byte `protobuf:"bytes,3,opt,name=csr_pem,json=csrPem,proto3" json:"csr_pem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollRequest) Reset() {
	*x = EnrollRequest{}
	mi := &file_fleet_v1_agent_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollRequest) ProtoMessage() {}

func (x *EnrollRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_agent_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollRequest.ProtoReflect.Descriptor instead.
func (*EnrollRequest) Descriptor() ([]byte, []int) {
	return file_fleet_v1_agent_proto_rawDescGZIP(), []int{18}
}

func (x *EnrollRequest) GetMachineId() string {
	if x != nil {
		return x.MachineId
	}
	return ""
}

func (x *EnrollRequest) GetToken() string {
	if x != nil {
		return x.Token
	}
	return ""
}

func (x *EnrollRequest) GetCsrPem() []byte {
	if x != nil {
		return x.CsrPem
	}
	return nil
}

type EnrollResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// PEM 编码的客户端证书（Fleet CA 签发）。
	CertPem []byte `protobuf:"bytes,1,opt,name=cert_pem,json=certPem,proto3" json:"cert_pem,omitempty"`
	// PEM 编码的 Fleet CA 证书（冗余下发，节点 bootstrap 时已持有）。
	CaPem []byte `protobuf:"bytes,2,opt,name=ca_pem,json=caPem,proto3" json:"ca_pem,omitempty"`
	// 证书到期时刻（unix 秒），供 agentd 规划续期窗口。
	NotAfterUnix  int64 `protobuf:"varint,3,opt,name=not_after_unix,json=notAfterUnix,proto3" json:"not_after_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnrollResponse) Reset() {
	*x = EnrollResponse{}
	mi := &file_fleet_v1_agent_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnrollResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnrollResponse) ProtoMessage() {}

func (x *EnrollResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_agent_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnrollResponse.ProtoReflect.Descriptor instead.
func (*EnrollResponse) Descriptor() ([]byte, []int) {
	return file_fleet_v1_agent_proto_rawDescGZIP(), []int{19}
}

func (x *EnrollResponse) GetCertPem() []byte {
	if x != nil {
		return x.CertPem
	}
	return nil
}

func (x *EnrollResponse) GetCaPem() []byte {
	if x != nil {
		return x.CaPem
	}
	return nil
}

func (x *EnrollResponse) GetNotAfterUnix() int64 {
	if x != nil {
		return x.NotAfterUnix
	}
	return 0
}

type RenewCertificateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CsrPem        []byte                 `protobuf:"bytes,1,opt,name=csr_pem,json=csrPem,proto3" json:"csr_pem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewCertificateRequest) Reset() {
	*x = RenewCertificateRequest{}
	mi := &file_fleet_v1_agent_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewCertificateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewCertificateRequest) ProtoMessage() {}

func (x *RenewCertificateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_agent_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewCertificateRequest.ProtoReflect.Descriptor instead.
func (*RenewCertificateRequest) Descriptor() ([]byte, []int) {
	return file_fleet_v1_agent_proto_rawDescGZIP(), []int{20}
}

func (x *RenewCertificateRequest) GetCsrPem() []byte {
	if x != nil {
		return x.CsrPem
	}
	return nil
}

type RenewCertificateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CertPem       []byte                 `protobuf:"bytes,1,opt,name=cert_pem,json=certPem,proto3" json:"cert_pem,omitempty"`
	NotAfterUnix  int64                  `protobuf:"varint,2,opt,name=not_after_unix,json=notAfterUnix,proto3" json:"not_after_unix,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RenewCertificateResponse) Reset() {
	*x = RenewCertificateResponse{}
	mi := &file_fleet_v1_agent_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RenewCertificateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RenewCertificateResponse) ProtoMessage() {}

func (x *RenewCertificateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_agent_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RenewCertificateResponse.ProtoReflect.Descriptor instead.
func (*RenewCertificateResponse) Descriptor() ([]byte, []int) {
	return file_fleet_v1_agent_proto_rawDescGZIP(), []int{21}
}

func (x *RenewCertificateResponse) GetCertPem() []byte {
	if x != nil {
		return x.CertPem
	}
	return nil
}

func (x *RenewCertificateResponse) GetNotAfterUnix() int64 {
	if x != nil {
		return x.NotAfterUnix
	}
	return 0
}

var File_fleet_v1_agent_proto protoreflect.FileDescriptor

const file_fleet_v1_agent_proto_rawDesc = "" +
	"\n" +
	"\x14fleet/v1/agent.proto\x12\bfleet.v1\x1a\x14fleet/v1/state.proto\"\xce\x03\n" +
	"\rAgentToServer\x12'\n" +
	"\x05hello\x18\x01 \x01(\v2\x0f.fleet.v1.HelloH\x00R\x05hello\x123\n" +
	"\theartbeat\x18\x02 \x01(\v2\x13.fleet.v1.HeartbeatH\x00R\theartbeat\x12@\n" +
	"\x0eobserved_state\x18\x03 \x01(\v2\x17.fleet.v1.ObservedStateH\x00R\robservedState\x12I\n" +
	"\x11operation_started\x18\x04 \x01(\v2\x1a.fleet.v1.OperationStartedH\x00R\x10operationStarted\x12L\n" +
	"\x12operation_progress\x18\x05 \x01(\v2\x1b.fleet.v1.OperationProgressH\x00R\x11operationProgress\x12F\n" +
	"\x10operation_result\x18\x06 \x01(\v2\x19.fleet.v1.OperationResultH\x00R\x0foperationResult\x121\n" +
	"\tlog_event\x18\a \x01(\v2\x12.fleet.v1.LogEventH\x00R\blogEventB\t\n" +
	"\apayload\"\xce\x03\n" +
	"\rServerToAgent\x12-\n" +
	"\awelcome\x18\x01 \x01(\v2\x11.fleet.v1.WelcomeH\x00R\awelcome\x12S\n" +
	"\x15desired_state_changed\x18\x02 \x01(\v2\x1d.fleet.v1.DesiredStateChangedH\x00R\x13desiredStateChanged\x12I\n" +
	"\x11execute_operation\x18\x03 \x01(\v2\x1a.fleet.v1.ExecuteOperationH\x00R\x10executeOperation\x12F\n" +
	"\x10cancel_operation\x18\x04 \x01(\v2\x19.fleet.v1.CancelOperationH\x00R\x0fcancelOperation\x12P\n" +
	"\x14operation_result_ack\x18\x05 \x01(\v2\x1c.fleet.v1.OperationResultAckH\x00R\x12operationResultAck\x12I\n" +
	"\x11request_inventory\x18\x06 \x01(\v2\x1a.fleet.v1.RequestInventoryH\x00R\x10requestInventoryB\t\n" +
	"\apayload\"\xbe\x02\n" +
	"\x05Hello\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x01 \x01(\tR\tmachineId\x12%\n" +
	"\x0eagentd_version\x18\x02 \x01(\tR\ragentdVersion\x12)\n" +
	"\x10protocol_version\x18\x03 \x01(\tR\x0fprotocolVersion\x12\x1a\n" +
	"\badapters\x18\x04 \x03(\tR\badapters\x129\n" +
	"\x18canonicalization_version\x18\x05 \x01(\tR\x17canonicalizationVersion\x12,\n" +
	"\x12last_inventory_seq\x18\x06 \x01(\x03R\x10lastInventorySeq\x12?\n" +
	"\fcapabilities\x18\a \x03(\v2\x1b.fleet.v1.AdapterCapabilityR\fcapabilities\"\xa6\x01\n" +
	"\x11AdapterCapability\x12\x16\n" +
	"\x06family\x18\x01 \x01(\tR\x06family\x12\x1e\n" +
	"\n" +
	"capability\x18\x02 \x01(\tR\n" +
	"capability\x12\x14\n" +
	"\x05state\x18\x03 \x01(\tR\x05state\x12+\n" +
	"\x11verified_versions\x18\x04 \x01(\tR\x10verifiedVersions\x12\x16\n" +
	"\x06reason\x18\x05 \x01(\tR\x06reason\"\xb0\x01\n" +
	"\aWelcome\x12)\n" +
	"\x10protocol_version\x18\x01 \x01(\tR\x0fprotocolVersion\x12<\n" +
	"\x1aheartbeat_interval_seconds\x18\x02 \x01(\x05R\x18heartbeatIntervalSeconds\x12<\n" +
	"\x1ainventory_interval_seconds\x18\x03 \x01(\x05R\x18inventoryIntervalSeconds\"I\n" +
	"\tHeartbeat\x12\x1a\n" +
	"\bsequence\x18\x01 \x01(\x03R\bsequence\x12 \n" +
	"\fsent_at_unix\x18\x02 \x01(\x03R\n" +
	"sentAtUnix\"5\n" +
	"\x13DesiredStateChanged\x12\x1e\n" +
	"\n" +
	"generation\x18\x01 \x01(\x03R\n" +
	"generation\"s\n" +
	"\x14DesiredStateSnapshot\x12\x1e\n" +
	"\n" +
	"generation\x18\x01 \x01(\x03R\n" +
	"generation\x12\x16\n" +
	"\x06digest\x18\x02 \x01(\tR\x06digest\x12#\n" +
	"\rsnapshot_json\x18\x03 \x01(\fR\fsnapshotJson\"q\n" +
	"\fPlanBaseline\x12<\n" +
	"\x1aobserved_projection_digest\x18\x01 \x01(\tR\x18observedProjectionDigest\x12#\n" +
	"\rinventory_seq\x18\x02 \x01(\x03R\finventorySeq\"\xf5\x01\n" +
	"\x10ExecuteOperation\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12-\n" +
	"\x12desired_generation\x18\x02 \x01(\x03R\x11desiredGeneration\x12:\n" +
	"\bsnapshot\x18\x03 \x01(\v2\x1e.fleet.v1.DesiredStateSnapshotR\bsnapshot\x12\x1f\n" +
	"\vplan_digest\x18\x04 \x01(\tR\n" +
	"planDigest\x122\n" +
	"\bbaseline\x18\x05 \x01(\v2\x16.fleet.v1.PlanBaselineR\bbaseline\"5\n" +
	"\x10OperationStarted\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\"z\n" +
	"\x11OperationProgress\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x12\n" +
	"\x04step\x18\x02 \x01(\tR\x04step\x12\x14\n" +
	"\x05phase\x18\x03 \x01(\tR\x05phase\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\"\xdc\x02\n" +
	"\x0fOperationResult\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\x12\x14\n" +
	"\x05phase\x18\x02 \x01(\tR\x05phase\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\tR\x06reason\x12\x18\n" +
	"\amessage\x18\x04 \x01(\tR\amessage\x12-\n" +
	"\x12desired_generation\x18\x05 \x01(\x03R\x11desiredGeneration\x120\n" +
	"\x06verify\x18\x06 \x01(\v2\x18.fleet.v1.VerifyEvidenceR\x06verify\x12&\n" +
	"\x0fstarted_at_unix\x18\a \x01(\x03R\rstartedAtUnix\x12(\n" +
	"\x10finished_at_unix\x18\b \x01(\x03R\x0efinishedAtUnix\x12+\n" +
	"\x11terminal_modifier\x18\t \x01(\tR\x10terminalModifier\"\x91\x02\n" +
	"\x0eVerifyEvidence\x12:\n" +
	"\x19desired_projection_digest\x18\x01 \x01(\tR\x17desiredProjectionDigest\x12<\n" +
	"\x1aobserved_projection_digest\x18\x02 \x01(\tR\x18observedProjectionDigest\x129\n" +
	"\x18canonicalization_version\x18\x03 \x01(\tR\x17canonicalizationVersion\x12#\n" +
	"\rinventory_seq\x18\x04 \x01(\x03R\finventorySeq\x12%\n" +
	"\x0eadapter_health\x18\x05 \x01(\tR\radapterHealth\"4\n" +
	"\x0fCancelOperation\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\"7\n" +
	"\x12OperationResultAck\x12!\n" +
	"\foperation_id\x18\x01 \x01(\tR\voperationId\"&\n" +
	"\x10RequestInventory\x12\x12\n" +
	"\x04full\x18\x01 \x01(\bR\x04full\"\\\n" +
	"\bLogEvent\x12\x14\n" +
	"\x05level\x18\x01 \x01(\tR\x05level\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12 \n" +
	"\fsent_at_unix\x18\x03 \x01(\x03R\n" +
	"sentAtUnix\"]\n" +
	"\rEnrollRequest\x12\x1d\n" +
	"\n" +
	"machine_id\x18\x01 \x01(\tR\tmachineId\x12\x14\n" +
	"\x05token\x18\x02 \x01(\tR\x05token\x12\x17\n" +
	"\acsr_pem\x18\x03 \x01(\fR\x06csrPem\"h\n" +
	"\x0eEnrollResponse\x12\x19\n" +
	"\bcert_pem\x18\x01 \x01(\fR\acertPem\x12\x15\n" +
	"\x06ca_pem\x18\x02 \x01(\fR\x05caPem\x12$\n" +
	"\x0enot_after_unix\x18\x03 \x01(\x03R\fnotAfterUnix\"2\n" +
	"\x17RenewCertificateRequest\x12\x17\n" +
	"\acsr_pem\x18\x01 \x01(\fR\x06csrPem\"[\n" +
	"\x18RenewCertificateResponse\x12\x19\n" +
	"\bcert_pem\x18\x01 \x01(\fR\acertPem\x12$\n" +
	"\x0enot_after_unix\x18\x02 \x01(\x03R\fnotAfterUnix2T\n" +
	"\x11FleetAgentService\x12?\n" +
	"\aConnect\x12\x17.fleet.v1.AgentToServer\x1a\x17.fleet.v1.ServerToAgent(\x010\x012\xb0\x01\n" +
	"\x16FleetEnrollmentService\x12;\n" +
	"\x06Enroll\x12\x17.fleet.v1.EnrollRequest\x1a\x18.fleet.v1.EnrollResponse\x12Y\n" +
	"\x10RenewCertificate\x12!.fleet.v1.RenewCertificateRequest\x1a\".fleet.v1.RenewCertificateResponseB=Z;github.com/shelwinnn/agent-fleet/api/proto/fleet/v1;fleetv1b\x06proto3"

var (
	file_fleet_v1_agent_proto_rawDescOnce sync.Once
	file_fleet_v1_agent_proto_rawDescData []byte
)

func file_fleet_v1_agent_proto_rawDescGZIP() []byte {
	file_fleet_v1_agent_proto_rawDescOnce.Do(func() {
		file_fleet_v1_agent_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fleet_v1_agent_proto_rawDesc), len(file_fleet_v1_agent_proto_rawDesc)))
	})
	return file_fleet_v1_agent_proto_rawDescData
}

var file_fleet_v1_agent_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_fleet_v1_agent_proto_goTypes = []any{
	(*AgentToServer)(nil),            // 0: fleet.v1.AgentToServer
	(*ServerToAgent)(nil),            // 1: fleet.v1.ServerToAgent
	(*Hello)(nil),                    // 2: fleet.v1.Hello
	(*AdapterCapability)(nil),        // 3: fleet.v1.AdapterCapability
	(*Welcome)(nil),                  // 4: fleet.v1.Welcome
	(*Heartbeat)(nil),                // 5: fleet.v1.Heartbeat
	(*DesiredStateChanged)(nil),      // 6: fleet.v1.DesiredStateChanged
	(*DesiredStateSnapshot)(nil),     // 7: fleet.v1.DesiredStateSnapshot
	(*PlanBaseline)(nil),             // 8: fleet.v1.PlanBaseline
	(*ExecuteOperation)(nil),         // 9: fleet.v1.ExecuteOperation
	(*OperationStarted)(nil),         // 10: fleet.v1.OperationStarted
	(*OperationProgress)(nil),        // 11: fleet.v1.OperationProgress
	(*OperationResult)(nil),          // 12: fleet.v1.OperationResult
	(*VerifyEvidence)(nil),           // 13: fleet.v1.VerifyEvidence
	(*CancelOperation)(nil),          // 14: fleet.v1.CancelOperation
	(*OperationResultAck)(nil),       // 15: fleet.v1.OperationResultAck
	(*RequestInventory)(nil),         // 16: fleet.v1.RequestInventory
	(*LogEvent)(nil),                 // 17: fleet.v1.LogEvent
	(*EnrollRequest)(nil),            // 18: fleet.v1.EnrollRequest
	(*EnrollResponse)(nil),           // 19: fleet.v1.EnrollResponse
	(*RenewCertificateRequest)(nil),  // 20: fleet.v1.RenewCertificateRequest
	(*RenewCertificateResponse)(nil), // 21: fleet.v1.RenewCertificateResponse
	(*ObservedState)(nil),            // 22: fleet.v1.ObservedState
}
var file_fleet_v1_agent_proto_depIdxs = []int32{
	2,  // 0: fleet.v1.AgentToServer.hello:type_name -> fleet.v1.Hello
	5,  // 1: fleet.v1.AgentToServer.heartbeat:type_name -> fleet.v1.Heartbeat
	22, // 2: fleet.v1.AgentToServer.observed_state:type_name -> fleet.v1.ObservedState
	10, // 3: fleet.v1.AgentToServer.operation_started:type_name -> fleet.v1.OperationStarted
	11, // 4: fleet.v1.AgentToServer.operation_progress:type_name -> fleet.v1.OperationProgress
	12, // 5: fleet.v1.AgentToServer.operation_result:type_name -> fleet.v1.OperationResult
	17, // 6: fleet.v1.AgentToServer.log_event:type_name -> fleet.v1.LogEvent
	4,  // 7: fleet.v1.ServerToAgent.welcome:type_name -> fleet.v1.Welcome
	6,  // 8: fleet.v1.ServerToAgent.desired_state_changed:type_name -> fleet.v1.DesiredStateChanged
	9,  // 9: fleet.v1.ServerToAgent.execute_operation:type_name -> fleet.v1.ExecuteOperation
	14, // 10: fleet.v1.ServerToAgent.cancel_operation:type_name -> fleet.v1.CancelOperation
	15, // 11: fleet.v1.ServerToAgent.operation_result_ack:type_name -> fleet.v1.OperationResultAck
	16, // 12: fleet.v1.ServerToAgent.request_inventory:type_name -> fleet.v1.RequestInventory
	3,  // 13: fleet.v1.Hello.capabilities:type_name -> fleet.v1.AdapterCapability
	7,  // 14: fleet.v1.ExecuteOperation.snapshot:type_name -> fleet.v1.DesiredStateSnapshot
	8,  // 15: fleet.v1.ExecuteOperation.baseline:type_name -> fleet.v1.PlanBaseline
	13, // 16: fleet.v1.OperationResult.verify:type_name -> fleet.v1.VerifyEvidence
	0,  // 17: fleet.v1.FleetAgentService.Connect:input_type -> fleet.v1.AgentToServer
	18, // 18: fleet.v1.FleetEnrollmentService.Enroll:input_type -> fleet.v1.EnrollRequest
	20, // 19: fleet.v1.FleetEnrollmentService.RenewCertificate:input_type -> fleet.v1.RenewCertificateRequest
	1,  // 20: fleet.v1.FleetAgentService.Connect:output_type -> fleet.v1.ServerToAgent
	19, // 21: fleet.v1.FleetEnrollmentService.Enroll:output_type -> fleet.v1.EnrollResponse
	21, // 22: fleet.v1.FleetEnrollmentService.RenewCertificate:output_type -> fleet.v1.RenewCertificateResponse
	20, // [20:23] is the sub-list for method output_type
	17, // [17:20] is the sub-list for method input_type
	17, // [17:17] is the sub-list for extension type_name
	17, // [17:17] is the sub-list for extension extendee
	0,  // [0:17] is the sub-list for field type_name
}

func init() { file_fleet_v1_agent_proto_init() }
func file_fleet_v1_agent_proto_init() {
	if File_fleet_v1_agent_proto != nil {
		return
	}
	file_fleet_v1_state_proto_init()
	file_fleet_v1_agent_proto_msgTypes[0].OneofWrappers = []any{
		(*AgentToServer_Hello)(nil),
		(*AgentToServer_Heartbeat)(nil),
		(*AgentToServer_ObservedState)(nil),
		(*AgentToServer_OperationStarted)(nil),
		(*AgentToServer_OperationProgress)(nil),
		(*AgentToServer_OperationResult)(nil),
		(*AgentToServer_LogEvent)(nil),
	}
	file_fleet_v1_agent_proto_msgTypes[1].OneofWrappers = []any{
		(*ServerToAgent_Welcome)(nil),
		(*ServerToAgent_DesiredStateChanged)(nil),
		(*ServerToAgent_ExecuteOperation)(nil),
		(*ServerToAgent_CancelOperation)(nil),
		(*ServerToAgent_OperationResultAck)(nil),
		(*ServerToAgent_RequestInventory)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fleet_v1_agent_proto_rawDesc), len(file_fleet_v1_agent_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_fleet_v1_agent_proto_goTypes,
		DependencyIndexes: file_fleet_v1_agent_proto_depIdxs,
		MessageInfos:      file_fleet_v1_agent_proto_msgTypes,
	}.Build()
	File_fleet_v1_agent_proto = out.File
	file_fleet_v1_agent_proto_goTypes = nil
	file_fleet_v1_agent_proto_depIdxs = nil
}
