// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// PROVENANCE (KM-22)：本文件按 protoc-gen-go-grpc v1.5.1 的输出格式手写维护——
// 交付环境离线、无该插件可执行；api/proto/gen.sh 在插件可用的环境中执行
// `protoc --go-grpc_out=...` 会再生成并覆盖本文件，届时以插件输出为准。
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc              (unknown)
// source: fleet/v1/agent.proto

package fleetv1

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file and the grpc package
// are compatible.
const _ = grpc.SupportPackageIsVersion9

const (
	FleetAgentService_Connect_FullMethodName               = "/fleet.v1.FleetAgentService/Connect"
	FleetEnrollmentService_Enroll_FullMethodName           = "/fleet.v1.FleetEnrollmentService/Enroll"
	FleetEnrollmentService_RenewCertificate_FullMethodName = "/fleet.v1.FleetEnrollmentService/RenewCertificate"
)

// FleetAgentServiceClient is the client API for FleetAgentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FleetAgentServiceClient interface {
	// Connect 是唯一的逻辑长连接：重连必以 Hello + 全量 ObservedState 开始（§5.2）。
	// 同一 machineId 已有活跃流时第二条流被拒绝并产生告警（§4.6）。
	Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentToServer, ServerToAgent], error)
}

type fleetAgentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFleetAgentServiceClient(cc grpc.ClientConnInterface) FleetAgentServiceClient {
	return &fleetAgentServiceClient{cc}
}

func (c *fleetAgentServiceClient) Connect(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AgentToServer, ServerToAgent], error) {
	stream, err := c.cc.NewStream(ctx, &FleetAgentService_ServiceDesc.Streams[0], FleetAgentService_Connect_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &fleetAgentServiceConnectClient{ClientStream: stream}
	return x, nil
}

type fleetAgentServiceConnectClient struct {
	grpc.ClientStream
}

func (x *fleetAgentServiceConnectClient) Send(m *AgentToServer) error {
	return x.ClientStream.SendMsg(m)
}

func (x *fleetAgentServiceConnectClient) Recv() (*ServerToAgent, error) {
	m := new(ServerToAgent)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

// FleetAgentServiceServer is the server API for FleetAgentService service.
type FleetAgentServiceServer interface {
	// Connect 是唯一的逻辑长连接：重连必以 Hello + 全量 ObservedState 开始（§5.2）。
	// 同一 machineId 已有活跃流时第二条流被拒绝并产生告警（§4.6）。
	Connect(grpc.BidiStreamingServer[AgentToServer, ServerToAgent]) error
	mustEmbedUnimplementedFleetAgentServiceServer()
}

// UnimplementedFleetAgentServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFleetAgentServiceServer struct{}

func (UnimplementedFleetAgentServiceServer) Connect(grpc.BidiStreamingServer[AgentToServer, ServerToAgent]) error {
	return status.Errorf(codes.Unimplemented, "method Connect not implemented")
}

func (UnimplementedFleetAgentServiceServer) mustEmbedUnimplementedFleetAgentServiceServer() {}

// UnsafeFleetAgentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is discouraged as it breaks forwards compatibility, and the interface itself is deprecated.
type UnsafeFleetAgentServiceServer interface {
	mustEmbedUnimplementedFleetAgentServiceServer()
}

func RegisterFleetAgentServiceServer(s grpc.ServiceRegistrar, srv FleetAgentServiceServer) {
	s.RegisterService(&FleetAgentService_ServiceDesc, srv)
}

func _FleetAgentService_Connect_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(FleetAgentServiceServer).Connect(&fleetAgentServiceConnectServer{stream})
}

type fleetAgentServiceConnectServer struct {
	grpc.ServerStream
}

func (x *fleetAgentServiceConnectServer) Send(m *ServerToAgent) error {
	return x.ServerStream.SendMsg(m)
}

func (x *fleetAgentServiceConnectServer) Recv() (*AgentToServer, error) {
	m := new(AgentToServer)
	if err := x.ServerStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

var FleetAgentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fleet.v1.FleetAgentService",
	HandlerType: (*FleetAgentServiceServer)(nil),
	Methods:     []grpc.MethodDesc{},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Connect",
			Handler:       _FleetAgentService_Connect_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "fleet/v1/agent.proto",
}

// FleetEnrollmentServiceClient is the client API for FleetEnrollmentService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FleetEnrollmentServiceClient interface {
	// Enroll：必须经 TLS 且校验服务端证书；token 是唯一身份证明（§7.5）。
	// 服务端在单事务内校验（存在/未过期/未用/machineId 匹配/CSR 指纹匹配）并作废 token。
	Enroll(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*EnrollResponse, error)
	// RenewCertificate：仅接受既有有效 mTLS 通道上的续期请求（§4.6）。
	RenewCertificate(ctx context.Context, in *RenewCertificateRequest, opts ...grpc.CallOption) (*RenewCertificateResponse, error)
}

type fleetEnrollmentServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFleetEnrollmentServiceClient(cc grpc.ClientConnInterface) FleetEnrollmentServiceClient {
	return &fleetEnrollmentServiceClient{cc}
}

func (c *fleetEnrollmentServiceClient) Enroll(ctx context.Context, in *EnrollRequest, opts ...grpc.CallOption) (*EnrollResponse, error) {
	cOpts := []grpc.CallOption{grpc.StaticMethod()}
	out := new(EnrollResponse)
	err := c.cc.Invoke(ctx, FleetEnrollmentService_Enroll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *fleetEnrollmentServiceClient) RenewCertificate(ctx context.Context, in *RenewCertificateRequest, opts ...grpc.CallOption) (*RenewCertificateResponse, error) {
	cOpts := []grpc.CallOption{grpc.StaticMethod()}
	out := new(RenewCertificateResponse)
	err := c.cc.Invoke(ctx, FleetEnrollmentService_RenewCertificate_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FleetEnrollmentServiceServer is the server API for FleetEnrollmentService service.
type FleetEnrollmentServiceServer interface {
	// Enroll：必须经 TLS 且校验服务端证书；token 是唯一身份证明（§7.5）。
	// 服务端在单事务内校验（存在/未过期/未用/machineId 匹配/CSR 指纹匹配）并作废 token。
	Enroll(context.Context, *EnrollRequest) (*EnrollResponse, error)
	// RenewCertificate：仅接受既有有效 mTLS 通道上的续期请求（§4.6）。
	RenewCertificate(context.Context, *RenewCertificateRequest) (*RenewCertificateResponse, error)
	mustEmbedUnimplementedFleetEnrollmentServiceServer()
}

// UnimplementedFleetEnrollmentServiceServer must be embedded to have forward compatible implementations.
type UnimplementedFleetEnrollmentServiceServer struct{}

func (UnimplementedFleetEnrollmentServiceServer) Enroll(context.Context, *EnrollRequest) (*EnrollResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Enroll not implemented")
}

func (UnimplementedFleetEnrollmentServiceServer) RenewCertificate(context.Context, *RenewCertificateRequest) (*RenewCertificateResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RenewCertificate not implemented")
}

func (UnimplementedFleetEnrollmentServiceServer) mustEmbedUnimplementedFleetEnrollmentServiceServer() {
}

// UnsafeFleetEnrollmentServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is discouraged as it breaks forwards compatibility, and the interface itself is deprecated.
type UnsafeFleetEnrollmentServiceServer interface {
	mustEmbedUnimplementedFleetEnrollmentServiceServer()
}

func RegisterFleetEnrollmentServiceServer(s grpc.ServiceRegistrar, srv FleetEnrollmentServiceServer) {
	s.RegisterService(&FleetEnrollmentService_ServiceDesc, srv)
}

func _FleetEnrollmentService_Enroll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnrollRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetEnrollmentServiceServer).Enroll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetEnrollmentService_Enroll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetEnrollmentServiceServer).Enroll(ctx, req.(*EnrollRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FleetEnrollmentService_RenewCertificate_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenewCertificateRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FleetEnrollmentServiceServer).RenewCertificate(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FleetEnrollmentService_RenewCertificate_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FleetEnrollmentServiceServer).RenewCertificate(ctx, req.(*RenewCertificateRequest))
	}
	return interceptor(ctx, in, info, handler)
}

var FleetEnrollmentService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "fleet.v1.FleetEnrollmentService",
	HandlerType: (*FleetEnrollmentServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Enroll",
			Handler:    _FleetEnrollmentService_Enroll_Handler,
		},
		{
			MethodName: "RenewCertificate",
			Handler:    _FleetEnrollmentService_RenewCertificate_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "fleet/v1/agent.proto",
}
