// state.proto — 观测状态消息（架构 v1.1.2 §8.2、§6.2；spec §11）。
// 节点 inventory 的最小消息集：机器信息 + Agent 实例占位
// （真实家族适配器与双侧投影摘要随第 4 片引入）。

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        v7.36.0
// source: fleet/v1/state.proto

package fleetv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// ObservedState 是一份全量观测（§5.2：每次重连后与周期任务上报）。
// inventorySeq 是节点本地单调序，仅用于单机内比较、丢弃乱序旧报文（FR-8.7）。
type ObservedState struct {
	state        protoimpl.MessageState `protogen:"open.v1"`
	InventorySeq int64                  `protobuf:"varint,1,opt,name=inventory_seq,json=inventorySeq,proto3" json:"inventory_seq,omitempty"`
	// 全量/增量标志；本片恒为全量（true）。
	Full bool `protobuf:"varint,2,opt,name=full,proto3" json:"full,omitempty"`
	// 若观测产生于某操作的 apply 之后，携带该 operationId（§4.4 门禁因果绑定）。
	OperationId string           `protobuf:"bytes,3,opt,name=operation_id,json=operationId,proto3" json:"operation_id,omitempty"`
	Machine     *MachineInfo     `protobuf:"bytes,4,opt,name=machine,proto3" json:"machine,omitempty"`
	Agents      []*AgentInstance `protobuf:"bytes,5,rep,name=agents,proto3" json:"agents,omitempty"`
	// 投影规范化版本（§7.1；本片占位，真实双侧投影摘要随第 4 片）。
	CanonicalizationVersion string `protobuf:"bytes,6,opt,name=canonicalization_version,json=canonicalizationVersion,proto3" json:"canonicalization_version,omitempty"`
	// 期望侧/观测侧受管投影摘要（ADR-1 双侧投影；本片占位为空）。
	DesiredProjectionDigest  string `protobuf:"bytes,7,opt,name=desired_projection_digest,json=desiredProjectionDigest,proto3" json:"desired_projection_digest,omitempty"`
	ObservedProjectionDigest string `protobuf:"bytes,8,opt,name=observed_projection_digest,json=observedProjectionDigest,proto3" json:"observed_projection_digest,omitempty"`
	unknownFields            protoimpl.UnknownFields
	sizeCache                protoimpl.SizeCache
}

func (x *ObservedState) Reset() {
	*x = ObservedState{}
	mi := &file_fleet_v1_state_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ObservedState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ObservedState) ProtoMessage() {}

func (x *ObservedState) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_state_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ObservedState.ProtoReflect.Descriptor instead.
func (*ObservedState) Descriptor() ([]byte, []int) {
	return file_fleet_v1_state_proto_rawDescGZIP(), []int{0}
}

func (x *ObservedState) GetInventorySeq() int64 {
	if x != nil {
		return x.InventorySeq
	}
	return 0
}

func (x *ObservedState) GetFull() bool {
	if x != nil {
		return x.Full
	}
	return false
}

func (x *ObservedState) GetOperationId() string {
	if x != nil {
		return x.OperationId
	}
	return ""
}

func (x *ObservedState) GetMachine() *MachineInfo {
	if x != nil {
		return x.Machine
	}
	return nil
}

func (x *ObservedState) GetAgents() []*AgentInstance {
	if x != nil {
		return x.Agents
	}
	return nil
}

func (x *ObservedState) GetCanonicalizationVersion() string {
	if x != nil {
		return x.CanonicalizationVersion
	}
	return ""
}

func (x *ObservedState) GetDesiredProjectionDigest() string {
	if x != nil {
		return x.DesiredProjectionDigest
	}
	return ""
}

func (x *ObservedState) GetObservedProjectionDigest() string {
	if x != nil {
		return x.ObservedProjectionDigest
	}
	return ""
}

// MachineInfo 是节点机器信息（写入 Machine status 的 os/arch/hostname/homeDir）。
type MachineInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Os            string                 `protobuf:"bytes,1,opt,name=os,proto3" json:"os,omitempty"`
	Arch          string                 `protobuf:"bytes,2,opt,name=arch,proto3" json:"arch,omitempty"`
	Hostname      string                 `protobuf:"bytes,3,opt,name=hostname,proto3" json:"hostname,omitempty"`
	HomeDir       string                 `protobuf:"bytes,4,opt,name=home_dir,json=homeDir,proto3" json:"home_dir,omitempty"`
	Kernel        string                 `protobuf:"bytes,5,opt,name=kernel,proto3" json:"kernel,omitempty"`
	CpuCount      int32                  `protobuf:"varint,6,opt,name=cpu_count,json=cpuCount,proto3" json:"cpu_count,omitempty"`
	TotalMemBytes int64                  `protobuf:"varint,7,opt,name=total_mem_bytes,json=totalMemBytes,proto3" json:"total_mem_bytes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MachineInfo) Reset() {
	*x = MachineInfo{}
	mi := &file_fleet_v1_state_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MachineInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MachineInfo) ProtoMessage() {}

func (x *MachineInfo) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_state_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MachineInfo.ProtoReflect.Descriptor instead.
func (*MachineInfo) Descriptor() ([]byte, []int) {
	return file_fleet_v1_state_proto_rawDescGZIP(), []int{1}
}

func (x *MachineInfo) GetOs() string {
	if x != nil {
		return x.Os
	}
	return ""
}

func (x *MachineInfo) GetArch() string {
	if x != nil {
		return x.Arch
	}
	return ""
}

func (x *MachineInfo) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *MachineInfo) GetHomeDir() string {
	if x != nil {
		return x.HomeDir
	}
	return ""
}

func (x *MachineInfo) GetKernel() string {
	if x != nil {
		return x.Kernel
	}
	return ""
}

func (x *MachineInfo) GetCpuCount() int32 {
	if x != nil {
		return x.CpuCount
	}
	return 0
}

func (x *MachineInfo) GetTotalMemBytes() int64 {
	if x != nil {
		return x.TotalMemBytes
	}
	return 0
}

// AgentInstance 是节点上一个 Agent 实例（本片为占位：仅上报 agentd 自身实例；
// Codex/OMP/OpenCode/ZCode 家族实例随第 4 片适配器接入）。
type AgentInstance struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Family        string                 `protobuf:"bytes,1,opt,name=family,proto3" json:"family,omitempty"`
	Version       string                 `protobuf:"bytes,2,opt,name=version,proto3" json:"version,omitempty"`
	Enabled       bool                   `protobuf:"varint,3,opt,name=enabled,proto3" json:"enabled,omitempty"`
	ConfigPath    string                 `protobuf:"bytes,4,opt,name=config_path,json=configPath,proto3" json:"config_path,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AgentInstance) Reset() {
	*x = AgentInstance{}
	mi := &file_fleet_v1_state_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AgentInstance) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AgentInstance) ProtoMessage() {}

func (x *AgentInstance) ProtoReflect() protoreflect.Message {
	mi := &file_fleet_v1_state_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AgentInstance.ProtoReflect.Descriptor instead.
func (*AgentInstance) Descriptor() ([]byte, []int) {
	return file_fleet_v1_state_proto_rawDescGZIP(), []int{2}
}

func (x *AgentInstance) GetFamily() string {
	if x != nil {
		return x.Family
	}
	return ""
}

func (x *AgentInstance) GetVersion() string {
	if x != nil {
		return x.Version
	}
	return ""
}

func (x *AgentInstance) GetEnabled() bool {
	if x != nil {
		return x.Enabled
	}
	return false
}

func (x *AgentInstance) GetConfigPath() string {
	if x != nil {
		return x.ConfigPath
	}
	return ""
}

var File_fleet_v1_state_proto protoreflect.FileDescriptor

const file_fleet_v1_state_proto_rawDesc = "" +
	"\n" +
	"\x14fleet/v1/state.proto\x12\bfleet.v1\"\x82\x03\n" +
	"\rObservedState\x12#\n" +
	"\rinventory_seq\x18\x01 \x01(\x03R\finventorySeq\x12\x12\n" +
	"\x04full\x18\x02 \x01(\bR\x04full\x12!\n" +
	"\foperation_id\x18\x03 \x01(\tR\voperationId\x12/\n" +
	"\amachine\x18\x04 \x01(\v2\x15.fleet.v1.MachineInfoR\amachine\x12/\n" +
	"\x06agents\x18\x05 \x03(\v2\x17.fleet.v1.AgentInstanceR\x06agents\x129\n" +
	"\x18canonicalization_version\x18\x06 \x01(\tR\x17canonicalizationVersion\x12:\n" +
	"\x19desired_projection_digest\x18\a \x01(\tR\x17desiredProjectionDigest\x12<\n" +
	"\x1aobserved_projection_digest\x18\b \x01(\tR\x18observedProjectionDigest\"\xc5\x01\n" +
	"\vMachineInfo\x12\x0e\n" +
	"\x02os\x18\x01 \x01(\tR\x02os\x12\x12\n" +
	"\x04arch\x18\x02 \x01(\tR\x04arch\x12\x1a\n" +
	"\bhostname\x18\x03 \x01(\tR\bhostname\x12\x19\n" +
	"\bhome_dir\x18\x04 \x01(\tR\ahomeDir\x12\x16\n" +
	"\x06kernel\x18\x05 \x01(\tR\x06kernel\x12\x1b\n" +
	"\tcpu_count\x18\x06 \x01(\x05R\bcpuCount\x12&\n" +
	"\x0ftotal_mem_bytes\x18\a \x01(\x03R\rtotalMemBytes\"|\n" +
	"\rAgentInstance\x12\x16\n" +
	"\x06family\x18\x01 \x01(\tR\x06family\x12\x18\n" +
	"\aversion\x18\x02 \x01(\tR\aversion\x12\x18\n" +
	"\aenabled\x18\x03 \x01(\bR\aenabled\x12\x1f\n" +
	"\vconfig_path\x18\x04 \x01(\tR\n" +
	"configPathB=Z;github.com/shelwinnn/agent-fleet/api/proto/fleet/v1;fleetv1b\x06proto3"

var (
	file_fleet_v1_state_proto_rawDescOnce sync.Once
	file_fleet_v1_state_proto_rawDescData []byte
)

func file_fleet_v1_state_proto_rawDescGZIP() []byte {
	file_fleet_v1_state_proto_rawDescOnce.Do(func() {
		file_fleet_v1_state_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_fleet_v1_state_proto_rawDesc), len(file_fleet_v1_state_proto_rawDesc)))
	})
	return file_fleet_v1_state_proto_rawDescData
}

var file_fleet_v1_state_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_fleet_v1_state_proto_goTypes = []any{
	(*ObservedState)(nil), // 0: fleet.v1.ObservedState
	(*MachineInfo)(nil),   // 1: fleet.v1.MachineInfo
	(*AgentInstance)(nil), // 2: fleet.v1.AgentInstance
}
var file_fleet_v1_state_proto_depIdxs = []int32{
	1, // 0: fleet.v1.ObservedState.machine:type_name -> fleet.v1.MachineInfo
	2, // 1: fleet.v1.ObservedState.agents:type_name -> fleet.v1.AgentInstance
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_fleet_v1_state_proto_init() }
func file_fleet_v1_state_proto_init() {
	if File_fleet_v1_state_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_fleet_v1_state_proto_rawDesc), len(file_fleet_v1_state_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_fleet_v1_state_proto_goTypes,
		DependencyIndexes: file_fleet_v1_state_proto_depIdxs,
		MessageInfos:      file_fleet_v1_state_proto_msgTypes,
	}.Build()
	File_fleet_v1_state_proto = out.File
	file_fleet_v1_state_proto_goTypes = nil
	file_fleet_v1_state_proto_depIdxs = nil
}
